baseURL = "https://anbidev.com/"
title   = "AnbiDev"

DefaultContentLanguage = "id"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

googleAnalytics = "UA-147560016-1"
disqusShortname = "anbidev"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

# [permalinks]
#   posts = "/posts/:title/"

[author]
  name = "AlifianAdexe"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  categories = "categories"
  tutorials = "tutorials"
  author = "authors"

[related]
  includeNewer = false
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 80

  [[related.indices]]
    name = "date"
    weight = 20

[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan 2006"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Sebuah website tempat membagikan ilmu kami tentang dunia informasi dan teknologi. Berisi tutorial pemrograman, opini, serta tips dan trik dalam dunia IT."
  keywords = "anbidev, anbidev.com, anbidev.tech, anbidev, ambidev, abidev, anbi dev, ambidex, anbidex, anbidef, alifianadexe, python, laravel, hamidmcs, satriab"
  images = [""]

  homeSubtitle = "Atas Nama Bangsa Indonesia Developer"
  homeQuotes = '"Stay Foolish In Diversity"'

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = ["css/custom.css", "css/bootstrap-grid.css",]
  customJS  = ["js/custom.js"]

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = true  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  # contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"
  themeColor = "#252627"

  [params.logo]
    logoText     = "/AnbiDev/"
    typeText     = '[ "/AnbiDev/", "/Python/", "/Kotlin/", "/Flutter/", "/CodeLife/" ]'
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "instagram"
    url  = "https://instagram.com/anbidev"

  [[params.social]]
    name = "facebook"
    url  = "https://facebook.com/anbidevofficial"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/anbidev"

  [[params.social]]
    name = "email"
    url  = "mailto:anbidev@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/AnbiDev"

  
  [[params.social]]
    name = "telegram"
    url  = "https://t.me/anbidev"
    

# [languages]
#   [languages.en]
#     subtitle  = "Atas Nama Bangsa Indonesia"
#     weight    = 1
#     copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

#   [languages.fr]
#     subtitle  = "Atas Nama Bangsa Indonesia"
#     weight    = 2
#     copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "blogs"
    name       = "Blog"
    url        = "blogs/"
    weight     = 1
    
  [[menu.main]]
    identifier = "tutorials"
    name       = "Tutorial"
    url        = "tutorials/"
    weight     = 2

    [[menu.main]]
      identifier = "python"
      name       = "Python"
      url        = "tutorials/python/"
      parent     = "tutorials"
      weight     = 1

    [[menu.main]]
      identifier = "machine-learning"
      name       = "Machine Learning"
      url        = "tutorials/machine-learning/"
      parent     = "tutorials"
      weight     = 2
    
    [[menu.main]]
      identifier = "c"
      name       = "C"
      url        = "tutorials/c/"
      parent     = "tutorials"
      weight     = 3
    

    [[menu.main]]
      identifier = "kotlin"
      name       = "Kotlin"
      url        = "tutorials/kotlin/"
      parent     = "tutorials"
      weight     = 4

    [[menu.main]]
      identifier = "android"
      name       = "Android"
      url        = "tutorials/android/"
      parent     = "tutorials"
      weight     = 5

    [[menu.main]]
      identifier = "git"
      name       = "Git"
      url        = "tutorials/git/"
      parent     = "tutorials"
      weight     = 6
    
    [[menu.main]]
      identifier = "php"
      name       = "PHP"
      url        = "tutorials/php/"
      parent     = "tutorials"
      weight     = 7
    
    [[menu.main]]
      identifier = "arduino"
      name       = "Arduino"
      url        = "tutorials/arduino/"
      parent     = "tutorials"
      weight     = 7

  
  

# Markdown renderer
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 3
        ordered = true

[outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "search"

# Hugo’s output control
[outputs]
    home = ["HTML", "RSS", "SearchIndex"]
   